### ISSUE TITLE
S3 output can’t find files it generates

### ISSUE THREAD

**Issue by vad** [logstash-plugins/logstash-output-s3#107]
Cross posted on: https://discuss.elastic.co/t/s3-output-cant-find-files-it-generates/68546

I'm using Logstash 5.0.2 (and .0.1 before) and I need to add an s3 output but I can't because randomly one of the file logstash generates cannot be found:

```
[2016-12-07T14:37:39,809][ERROR][logstash.outputs.s3      ] failed to upload, will re-enqueue /tmp/logstash/ls.s3.ip-172-31-45-248.2016-12-07T14.31.part0.txt for upload {:ex=>#<Errno::ENOENT: No such file or directory - /tmp/logstash/ls.s3.ip-172-31-45-248.2016-12-07T14.31.part0.txt>, :backtrace=>["org/jruby/RubyFile.java:370:in `initialize'", "org/jruby/RubyIO.java:1197:in `open'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-3.2.0/lib/logstash/outputs/s3.rb:175:in `write_on_bucket'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-3.2.0/lib/logstash/outputs/s3.rb:289:in `move_file_to_bucket'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-3.2.0/lib/logstash/outputs/s3.rb:454:in `upload_worker'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-3.2.0/lib/logstash/outputs/s3.rb:436:in `configure_upload_workers'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"]}
```
As it says Logstash "will re-enqueue" the file over and over again filling up the disk with log messages. This happens randomly: Logstash works for some time (minutes or hours) and then suddenly this happens.

This is my output configuration:

```ruby
if [type] == "my-log" {
  s3 {
    bucket => "mybucket"
    prefix => "logstash/bla/"
    size_file => 10485760  # rotate every 10M
    codec => line {
      format => "%{message}"
    }
  }
}
```

I'm on ubuntu 14.04. Oracle JVM:

```
# java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by ph** [comment]
@vad Can you do one of the following:

- run logstash with `--log.level` debug (this will make the output more verbose)
- update to the logstash-output-s3 to the latest version https://rubygems.org/gems/logstash-output-s3 `bin/logtash-plugin install --version 4.0.0 logstash-output-s3` should do the trick.

4.0.0 is a complete rewrite with better logging so we should see what is currently happening.

**Comment by jitran** [comment]
I experienced this error with the vanilla install of logstash 5.1.1. With my situation, I had more than one s3 {} output block (I'm trailing logstash atm..), but I had forgotten to specify a unique s3 **temporary_directory** path which caused a race condition when both output blocks tried to write to s3. Once I specified a unique temp path for both blocks, the re-enqueue error went away.

**Comment by ph** [comment]
@jitran Your explanation is correct, But this issue shouldn't occur in 4.0.0, since all generated files are prefixed with a UUID reducing the risk of collision.
