### ISSUE TITLE
S3 upload retry infinite loop

### ISSUE THREAD

**Issue by marcinc** [logstash-plugins/logstash-output-s3#143]
It seems that in crash restore scenario plugin can potentially go into an infinite loop when a file it expects no longer exists on disk. It could be potentially a result of some race condition when LS crash happens whereby file gets removed from disk before recovery threadpool gets to process it? In such situation any attempt to upload non-existent file to S3 would fail with exception which in turn logs error and [`retry`](https://github.com/logstash-plugins/logstash-output-s3/blob/7aa5a03baa3a5f74722d3c320d629b5e9e1b257f/lib/logstash/outputs/s3/uploader.rb#L39-L46) immediately. Note: Uploader currently doesn't utilise `TIME_BEFORE_RETRYING_SECONDS` even though it's defined.  

Also I wonder whether [`LogStash::Outputs::S3#upload_file`](https://github.com/logstash-plugins/logstash-output-s3/blob/7aa5a03baa3a5f74722d3c320d629b5e9e1b257f/lib/logstash/outputs/s3.rb#L341-L345) should also delete zero-byte files? `upload_file` only ever gets called on `close` or file rotation. 

- Version: 4.0.7
- Operating System: Fedora 25
- Config File:

```
output {
  s3{
    id => "some_id"
    access_key_id => "aws-key-id"
    secret_access_key => "aws-secret-key"
    bucket => "bucket-name"
    region => "eu-west-1"
    restore => true
    time_file => "10"
    size_file => "10485760"
    canned_acl => "private"
    codec => "json_lines"
    server_side_encryption => true
    server_side_encryption_algorithm => "aws:kms"
    validate_credentials_on_root_bucket => false
  }
}
```

- Sample Log:

```
[2017-05-14T23:03:34,089][ERROR][l.o.s3                   ] Uploading failed, retrying {:exception=>Errno::ENOENT, :message=>"No such file or directory - No such file or directory - /some/tmp/logstash/b86c6790-e671-400b-b8a3-7aadd2affd5a/ls.s3.5a834064-2486-4909-9171-cbcd5311ae94.2017-05-14T22.29.part0.txt", :path=>"/some/tmp/logstash/b86c6790-e671-400b-b8a3-7aadd2affd5a/ls.s3.5a834064-2486-4909-9171-cbcd5311ae94.2017-05-14T22.29.part0.txt", :backtrace=>["org/jruby/RubyFileTest.java:239:in `size'", "/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:31:in `upload'", "/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/object.rb:251:in `upload_file'", "/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.7/lib/logstash/outputs/s3/uploader.rb:38:in `upload'", "/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.7/lib/logstash/outputs/s3/uploader.rb:29:in `upload_async'", "org/jruby/RubyProc.java:281:in `call'", "/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-1.0.0-java/lib/concurrent/executor/java_executor_service.rb:94:in `run'", "Concurrent$$JavaExecutorService$$Job_754842726.gen:13:in `run'"]}
```

**Comment by webmat** [comment]
This issue was fixed by #144 and following the advice in [this comment](https://github.com/logstash-plugins/logstash-output-s3/pull/144#issuecomment-301888946).
