### ISSUE TITLE
JRuby 9k incompatiblity 

### ISSUE THREAD

**Issue by jakelandis** [logstash-plugins/logstash-output-s3#149]
When running against Logstash 6.x with JRuby 9k,  this plugin will not start. 

The following error (with the backtrace added in)
```
[2017-07-18T16:57:58,081][ERROR][logstash.outputs.s3      ] Error validating bucket write permissions! {:message=>"closed stream", :class=>"IOError", :backtrace=>["org/jruby/RubyFileTest.java:238:in `size'", "/Users/jake/workspace/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:31:in `upload'", "/Users/jake/workspace/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/object.rb:251:in `upload_file'", "/Users/jake/workspace/plugins/logstash-output-s3/lib/logstash/outputs/s3/write_bucket_permission_validator.rb:44:in `upload_test_file'", "/Users/jake/workspace/plugins/logstash-output-s3/lib/logstash/outputs/s3/write_bucket_permission_validator.rb:18:in `valid?'", "/Users/jake/workspace/plugins/logstash-output-s3/lib/logstash/outputs/s3.rb:200:in `register'", "/Users/jake/workspace/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "/Users/jake/workspace/logstash/logstash-core/lib/logstash/output_delegator.rb:41:in `register'", "/Users/jake/workspace/logstash/logstash-core/lib/logstash/pipeline.rb:369:in `register_plugin'", "/Users/jake/workspace/logstash/logstash-core/lib/logstash/pipeline.rb:380:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/jake/workspace/logstash/logstash-core/lib/logstash/pipeline.rb:380:in `register_plugins'", "/Users/jake/workspace/logstash/logstash-core/lib/logstash/pipeline.rb:389:in `start_workers'", "/Users/jake/workspace/logstash/logstash-core/lib/logstash/pipeline.rb:314:in `run'", "/Users/jake/workspace/logstash/logstash-core/lib/logstash/pipeline.rb:274:in `block in start'"]}
```

It seems that RubyFileTest.java checks the file size, which requires the file to be open.

**Comment by leo100** [comment]
Hello,

Guessing I get this from the logstash 6.2.1 and S3 plugin?

2018-02-22T12:42:15,671][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
/app/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/documenter/has_many_operation_documenter.rb:7: warning: `+' after local variable or literal is interpreted as binary operator
/app/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/documenter/has_many_operation_documenter.rb:7: warning: even though it seems like unary operator

**Comment by sanky186** [comment]
I get an idea of the issue.. How to fix this ?.. Upgrade .. Downgarde ?
