### ISSUE TITLE
Logstash crashes with [FATAL][logstash.runner ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `__jcreate_meta!' for #<LogStash::Outputs::S3::FileRepository::FactoryInitializer:0x15d5a412>>

### ISSUE THREAD

**Issue by geekpete** [logstash-plugins/logstash-output-s3#156]
- Version:
  - Official Logstash 5.5.0 docker image (docker.elastic.co/logstash/logstash:5.5.0)
  - this ships with logstash-output-s3 (4.0.8) 
- Operating System: Centos (from official docker image)
- Config File: minimal env vars/config, listed below.
- Sample Data:
- Steps to Reproduce:
  - started logstash docker container with s3 output running and after a number of hours a fatal crash occurs. Repeats if container is restarted after a some hours of uptime again.
  - crash seen when used with Kubernetes in an AWS environment.

Sample crash error log:

```
[2017-09-05T00:37:45,393][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600} 
[2017-09-05T00:37:48,504][FATAL][logstash.runner ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `__jcreate_meta!' for #<LogStash::Outputs::S3::FileRepository::FactoryInitializer:0x15d5a412>>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.8/lib/logstash/outputs/s3/file_repository.rb:82:in `get_factory'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.8/lib/logstash/outputs/s3/file_repository.rb:86:in `get_file'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.8/lib/logstash/outputs/s3.rb:236:in `multi_receive_encoded'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.8/lib/logstash/outputs/s3.rb:231:in `multi_receive_encoded'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:420:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:419:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:330:in `start_workers'"]} 
```

Logstash docker container started in fairly basic way:

no environmental variables used except the following:
`LS_JAVA_OPTS=-Djava.net.preferIPv4Stack=true`
 
logstash.yml:
```
http.host: 0.0.0.0
xpack.monitoring.enabled: false
```

logstash config:
```
input { 
http { 
port => 5000 
} 
} 

filter { 
json { 
source => "message" 
target => "log" 
skip_on_invalid_json => true 
} 
mutate { 
remove_field => [ "message"] 
} 
} 

output { 
elasticsearch { 
hosts => ["${ES_HOST}:${ES_PORT}"] 
index => "mytest-%{+YYYY.MM.dd}" 
} 

s3 { 
bucket => "testing-xxxxxxxxxxxxxxx-logging-yyyyyy-zz" 
prefix => "mytest/%{+YYYY.MM.dd}" 
region => "my-amazon-region-here" 
codec => "json" 
} 
}
```

**Comment by original-brownbear** [comment]
@geekpete figured it out :) https://github.com/logstash-plugins/logstash-output-s3/blob/master/lib/logstash/outputs/s3/file_repository.rb#L43 is guilty here. We're implementing `java.util.function.Function` (__jcreate_meta is a method around implementing Java interfaces in Jruby) and somehow that doesn't work out so well in 1.7 (maybe because of JDK 8 `default` methods?).
Will refactor this to not use the Java implementation for now, so that we have a safe fix asap :)
On it

**Comment by geekpete** [comment]
Thanks heaps!

**Comment by original-brownbear** [comment]
@geekpete fixed and published here https://rubygems.org/gems/logstash-output-s3/versions/4.0.11

>  Or put another way, is this something we could search for in other plugins and also fix?

Yes but man, that' going to be a tricky search. Basically, you'd have to look at every call to a Java API and see if we are using a Ruby object as param, that doesn't include the necessary interface.
Though even then, as we saw here, this isn't going to raise an error every time, only if the timing of JIT compilation is unfortunate :)
I'll keep an eye out for these though.

**Comment by geekpete** [comment]
Thanks heaps!
