### ISSUE TITLE
S3 wastes CPU with "Uploading failed, retrying", but succeeded?

### ISSUE THREAD

**Issue by sinzui** [logstash-plugins/logstash-output-s3#171]
We see that the s3 plugin uses 35 to 70% of the CPU. The logstash logs are spammed with errors like this, but we see all the log messages are uploaded to s3.

[2018-02-27T14:45:27,945][ERROR][logstash.outputs.s3      ] Uploading failed, retrying {:exception=>Aws::S3::Errors::InvalidArgument, :message=>"x-amz-server-side-encryption header is not supported for this operation.", :path=>"/data/1/logstash/tmp/libnetty-tcnative-linux-x86_647838224160814951883.so", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/s3_accelerate.rb:33:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/plugins/response_target.rb:21:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/request.rb:70:in `send_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.3.22/lib/seahorse/client/base.rb:207:in `put_object'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:42:in `put_object'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:49:in `open_file'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:41:in `put_object'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/file_uploader.rb:34:in `upload'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.3.22/lib/aws-sdk-resources/services/s3/object.rb:251:in `upload_file'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.13/lib/logstash/outputs/s3/uploader.rb:38:in `upload'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-s3-4.0.13/lib/logstash/outputs/s3/uploader.rb:29:in `upload_async'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-1.0.5-java/lib/concurrent/executor/java_executor_service.rb:94:in `run'", "Concurrent$$JavaExecutorService$$Job_736309745.gen:13:in `run'"]}

So while CPU is very high and the logs are spammed, otherwise see s3 successful. We have set `logger.s3output.level = FATAL ` to keep the logs usable, but we might be missing real critical issues.

- Version: logstash 5.6.8 and 6.2.2
- Operating System: Centos
- Config File (if you have sensitive info, please remove it):

output {
  if [type] == 'system.sys' {
    s3 {
      id => "s3.logs.test.curtis"
      region => "us-east-1"
      bucket => "foobar"
      server_side_encryption => true
      server_side_encryption_algorithm => "aws:kms"
      ssekms_key_id => "arn:aws:kms:us-east-1:barbaz:key/bzrqux"
      validate_credentials_on_root_bucket => false
      canned_acl => "private"
      prefix => "test.curtis"
      size_file => 5242880
      time_file => 5
      codec => "line"
      temporary_directory => "/data/1/logstash/tmp"
    }
  }
}

- Sample Data: None
- Steps to Reproduce:

**Comment by marioluan** [comment]
@sinzui 
How many events per second/minute are you processing?
Is it possible to share the steps to reproduce it?

**Comment by sinzui** [comment]
@marioluan we were seeing more than 500 messages a minute.

We addressed this by enabling default SSE on the bucket, then removing server_side_encryption, server_side_encryption_algorithm, ssekms_key_id, validate_credentials_on_root_bucket. The files are still encrypted, but the plugin doesn't try to do the bucket checks with keys.

With this configuration change the plugin uses about 2% of CPU with occassional spikes of 20%.
