### ISSUE TITLE
Unsupported Accept-Encoding specified

### ISSUE THREAD

**Issue by freeNestor** [logstash-plugins/logstash-output-s3#264]
We want to use logstash outputting messages to s3 recently. We've encountered a problem in the test. Anyone could help?

**Applicable branches**:
logstash 8.16.1

**Config**:
output {
      s3｛
          access_key_id => "xxxx"
          secret_access_key => "xxxxx"
          endpoint => "http://host.com"
          bucket => "test"
          validate_credentials_on_root _bucket => false
          encoding => "none"   # tried "gzip" not working
          prefix => "2024"
          #codec => "json_lines"
       }
}
**Failure except**:
```
:exception=>Aws::S3::Errors::InvalidArgument, :message=>"Unsupported Accept-Encoding specified", 
:path=>"/tmp/logstash/53ae4928-ecf7-40a6-a2fa-c8519d9882c8/2024/ls.s3.f6702ff9-946e-4a24-a0cb-a6ff41295c36.2024-12-03T15.38.part0.txt", 
:backtrace=>["/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-s3-1.169.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-s3-1.169.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-s3-1.169.0/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/aws-sdk-core/plugins/invocation_id.rb:16:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/seahorse/client/plugins/request_callback.rb:89:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'", "/home/logstash/logstash-8.16.1/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.211.0/lib/aws-s
```

**Comment by robbavey** [comment]
@freeNestor Is this attempting to write to Amazon S3, or an S3-compatible storage system? The Logstash S3 output is only supported on actual S3.

Also, would you mind re-opening this issue in the [AWS Integration repo](https://github.com/logstash-plugins/logstash-integration-aws), which is the latest home for the S3 output - individual AWS plugins, such as the S3 output have been folded up into the integration plugin
