### ISSUE TITLE
Test failing because of obsolete configuration

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-output-s3#40]
http://build-eu-1.elasticsearch.org/view/LS%20Master/job/Logstash_Master_Default_Plugins/612/console
```
  1) LogStash::Outputs::S3#generate_temporary_filename should not add the tags to the filename
     Failure/Error: s3 = LogStash::Outputs::S3.new(config)
     LogStash::ConfigurationError:
       The setting `tags` in plugin `s3` is obsolete and is no longer available. You can achieve similar behavior with the new conditionals, like: `if "sometag" in [tags] { s3 { ... } }` If you have any questions about this, you are invited to visit https://discuss.elastic.co/c/logstash and ask.
     # ./lib/logstash/config/mixin.rb:82:in `config_init'
     # ./lib/logstash/config/mixin.rb:66:in `config_init'
     # ./lib/logstash/outputs/base.rb:44:in `initialize'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.1/spec/outputs/s3_spec.rb:84:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.7/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

**Comment by ph** [comment]
duplicate of #39
