### ISSUE TITLE
logstash-output-s3 plugin error when region is "cn-north-1"

### ISSUE THREAD

**Issue by wangxpeng** [logstash-plugins/logstash-output-s3#72]
I think this is a bug.
When I start the logstash, error log: 
"The error reported is: \n initialize: name or service not known"
my logstash config file:

...
region => "cn-north-1"
...

I check the request url: 
https://xxx.s3-cn-north-1.amazonaws.com
But when region is "cn-north-1", the url should be:
https://xxx.s3.cn-north-1.amazonaws.com.cn

Then I check the code, and found: 
vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.4/lib/logstash/outputs/s3.rb
ln 143:
:s3_endpoint => region_to_use == 'us-east-1' ? 's3.amazonaws.com' : "s3-#{region_to_use}.amazonaws.com

Then I modify this code, start success.

**Comment by dioxys** [comment]
Originally posted this to the logstash repo, I'm adding it here instead.
Looks like we came to the same conclusion.

---


I've got a file and UDP input.
A s3 output to Tokyo working fine, but when i add another s3 output to a chinese bucket, i get the error below.

Tested with both logstash 1.5.6-1 and 2.2.2 on Amazon linux. 

Google fu tells me to look up the udp input, which maps fine and isn't allocated before starting the logstash process.With just one s3 output this works fine.

AWS CLI actions like cp, mv, list and rm all work fine with the same credentials.
Could it be that the cn-north-1 regions isn't mapped to the right endpoint or something?

```
input {
udp {
    port      => 9500
    type      => "redacted"
    add_field => [ "env", "prod" ]
  }
}
```


```
output  {
  s3 {
    bucket            => "redacted"
    region            => "ap-northeast-1"
    access_key_id     => "redacted"
    secret_access_key => "redacted"
    time_file         => 5
    codec             => "json"
  }
 s3 {
    bucket            => "redacted"
    region            => "cn-north-1"
    access_key_id     => "redacted"
    secret_access_key => "redacted"
    time_file         => 5
    codec             => "json"
  }
}`
```


```
`Registering s3 output {:bucket=>"redacted", :endpoint_region=>"cn-north-1", :level=>:info, :file=>"logstash/outputs/s3.rb", :line=>"128", :method=>"aws_s3_config"}
S3: Creating a test file on S3 {:level=>:debug, :file=>"logstash/outputs/s3.rb", :line=>"226", :method=>"test_s3_write"}
S3: ready to write file in bucket {:remote_filename=>"logstash-programmatic-access-test-object-1458553169", :bucket=>"redacted", :level=>:debug, :file=>"logstash/outputs/s3.rb", :line=>"154", :method=>"write_on_bucket"}
The error reported is:
  initialize: name or service not known
org/jruby/ext/socket/RubyTCPSocket.java:129:in `initialize'
org/jruby/RubyIO.java:1179:in `open'
/opt/logstash-2.2.2/vendor/jruby/lib/ruby/1.9/net/http.rb:763:in `connect'
org/jruby/ext/timeout/Timeout.java:115:in `timeout'
/opt/logstash-2.2.2/vendor/jruby/lib/ruby/1.9/net/http.rb:763:in `connect'
/opt/logstash-2.2.2/vendor/jruby/lib/ruby/1.9/net/http.rb:756:in `do_start'
/opt/logstash-2.2.2/vendor/jruby/lib/ruby/1.9/net/http.rb:751:in `start'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/connection_pool.rb:327:in `start_session'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/connection_pool.rb:127:in `session_for'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/http/net_http_handler.rb:56:in `handle'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:253:in `make_sync_request'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:289:in `retry_server_errors'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/s3/region_detection.rb:11:in `retry_server_errors'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:249:in `make_sync_request'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:509:in `client_request'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:391:in `log_client_request'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:477:in `client_request'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:373:in `return_or_raise'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `put_object'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/aws-sdk-v1-1.66.0/lib/aws/s3/s3_object.rb:1765:in `write_with_put_object'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.4/lib/logstash/outputs/s3.rb:160:in `write_on_bucket'
org/jruby/RubyIO.java:1183:in `open'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.4/lib/logstash/outputs/s3.rb:156:in `write_on_bucket'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.4/lib/logstash/outputs/s3.rb:236:in `test_s3_write'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/output_delegator.rb:29:in `initialize'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:403:in `plugin'
(eval):27:in `initialize'
org/jruby/RubyKernel.java:1079:in `eval'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:57:in `initialize'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/agent.rb:172:in `execute'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/runner.rb:90:in `run'
org/jruby/RubyProc.java:281:in `call'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/runner.rb:95:in `run'
org/jruby/RubyProc.java:281:in `call'
/opt/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'
```

**Comment by wangxpeng** [comment]
@hajhatten I think this is a same problem.
You can have a try like this: 
vendor/bundle/jruby/1.9/gems/logstash-output-s3-2.0.4/lib/logstash/outputs/s3.rb
ln143: 
:s3_endpoint => region_to_use == 'us-east-1' ? 's3.amazonaws.com' : "s3-#{region_to_use}.amazonaws.com

modify the code upon like this : 
:s3_endpoint => region_to_use == 'us-east-1' ? 's3.amazonaws.com' : ( region_to_use == 'cn-north-1' ? "s3.#{region_to_use}.amazonaws.com.cn" : "s3-#{region_to_use}.amazonaws.com")

Thank you!
(My English is so terrible and hope you can understand^_^)
