### ISSUE TITLE
[Windows] Skipping events with the `size_file` option

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-output-s3#8]
Failures:

  1) LogStash::Outputs::S3 when rotating the temporary file doesn't skip events
if using the size_file option
     Failure/Error: expect(events_written_count).to eq(event_count)

       expected: 12373
            got: 0

       (compared using ==)
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\Administrator\logstash\lib\logstash\runner.rb:170:in `run'

Finished in 2 minutes 37.8 seconds
21 examples, 1 failure

Failed examples:

**Comment by ph** [comment]
Fixed in https://github.com/elasticsearch/logstash/pull/2507
